'''
- Deal with non-valid points, number of points per lane --> Done
- Normalizing labels dataset or gt labels correspond to image?! --> Done
- Writing a Video based on a new images --> Done
- Create Figure for drawing train loss, write a callback function
- How to resize picture, keep aspect ratio?
- Crop the image by the height of lane available on json file
'''
'''
0313---2858 files
0531---358 files
0601---410 files
'''

from utils.Augmentation import Augmentation

No_images = 500 # number of images to be generated by augmentation
sp_img_shape = (128,128) # size of resized image after preprocess
aug1 = Augmentation(sp_img_shape)
aug1.generate(No_images)
aug1.check_code()    # just for checking the corectness of the code
